### ISSUE TITLE
npm install registry gives 401 error as using a private registry.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [zowe/zowe-cli-cics-plugin#23]
The npm install fails like this 

npm install
npm ERR! code E401
npm ERR! 404 401 Unauthorized: js-yaml@3.9.0

npm ERR! A complete log of this run can be found in:...

This is due to the registry being set as
registry=https://gizaartifactory.jfrog.io/gizaartifactory/api/npm/npm-release/

To resolve I set the registry to https://registry.npmjs.org 

The supplied npm repository should be accessible or use the public one.

**Comment by zFernand0** [comment]
The `.npmrc` file now points to the open Zowe JFrog registry 😋 
https://github.com/zowe/zowe-cli-cics-plugin/blob/master/.npmrc#L2
