### ISSUE TITLE
Install a CICS URIMAP

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli-cics-plugin#48]
Create a new zowe CLI command to install a CICS URIMAP resource
- size = 5
- assumptions
    - Must implement the following options
        - 10 CICS global options
        - TARGET
        - The CMCI API only permits USAGE=LOCAL for URIMAP resources. We will NOT supply a USAGE option to our end user. USAGE=LOCAL will be hard-coded
    - We will not implement these 7 additional options
        - ADDTOGRP 
        - FORCEINS
        - MODE
        - NOTIFY
        - OVERRIDE
        - OVERTYPE
        - RELATED
        - STATECHK
    - Will be started after DEFINE (we will have learned stuff about CICS)
- Consult with John L. to select option names
- implement zowe API to call the right CMCI functions
- implement zowe CLI to call the right zowe API function
- confirm that existing GET command works for URIMAP resources
- doc CLI
- automated tests
- helpful info
    - https://www.ibm.com/support/knowledgecenter/SSGMCP_5.5.0/reference/cpsm-restables/URIMPDEFtab.html
    - https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.5.0/reference/cmci/clientapi_installerror.html
    - https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.5.0/reference/cmci/actionsCSDresource.html
    - https://www.ibm.com/support/knowledgecenter/SSGMCP_5.5.0/system-programming/cpsm/instprm.html

**Comment by tjohnsonBCM** [comment]
Example of invoking REST API to install URIMAP:
`PUT <host>:<port>/CICSSystemManagement/CICSDefinitionURIMap/CICCMCI2?CRITERIA=(NAME=ABCD)&PARAMETER=CSDGROUP(MYGRP)`
where region name = "CICCMCI2", URIMap name = "ABCD", and CICS group name = "MYGRP"
with the following XML body:
```
<request>
  <action name="CSDINSTALL">
  </action>
</request>
```
