### ISSUE TITLE
Enable a CICS URIMAP

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli-cics-plugin#49]
Create a new zowe CLI command to enable a CICS URIMAP resource
- size = 5
- assume
    - 10 CICS global options
- implement zowe API to call the right CMCI functions
- implement zowe CLI to call the right zowe API function
- doc CLI
- automated tests
- helpful info
    - https://www.ibm.com/support/knowledgecenter/SSGMCP_5.5.0/reference/cpsm-restables/URIMAPtab.html

**Comment by tjohnsonBCM** [comment]
Example of invoking REST API to enable URIMAP:
`PUT <host>:<port>/CICSSystemManagement/CICSURIMap/CICCMCI2?CRITERIA=(NAME=ABCD)`
where region name = "CICCMCI2" and URIMap name = "ABCD"
with the following XML body:
```
<request>
  <action name="ENABLE">
  </action>
</request>
```

**Comment by tjohnsonBCM** [comment]
Resolved by #64
