### ISSUE TITLE
Delete a CICS URIMAP

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli-cics-plugin#52]
Create a new zowe CLI command to delete a CICS URIMAP resource
- size = 5
- assume
    - 10 parameters
    - Programs and transactions have a delete, so we should too?
- implement zowe API to call the right CMCI functions
- implement zowe CLI to call the right zowe API functions
- doc CLI
- automated tests
- helpful info
    - https://www.ibm.com/support/knowledgecenter/SSGMCP_5.5.0/reference/cpsm-restables/URIMAPtab.html

**Comment by tjohnsonBCM** [comment]
Example of invoking REST API to delete URIMAP:
`DELETE <host>:<port>/CICSSystemManagement/CICSDefinitionURIMap/CICCMCI2?CRITERIA=(NAME=ABCD)&PARAMETER=CSDGROUP(MYGRP)`
where region name = "CICCMCI2", URIMap name = "ABCD", and CICS group name = "MYGRP"
