### ISSUE TITLE
Define a CICS URIMAP

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli-cics-plugin#53]
Create a new zowe CLI command to define a CICS URIMAP resource

- size = 13
- assumptions
   - Must implement the following common options
        - 10 CICS global options
        - URIMAP
        - GROUP
        - PATH
        - SCHEME
        - do not implement 2 additional options
    - Must implement the following command objects with  these options
        - URI-server
            - HOST
            - PROGRAM
            - do not implement 12 additional options
        - URI-client
            - HOST
            - do not implement 2 additional options
        - URI-pipeline
            - HOST
            - PIPELINE
            - do not implement 6 additional options
- The programmer is not familiar with CICS operations and must learn the correct behaviors
- Consult with John L. to select command object names and option names
- implement zowe API to call the right CMCI functions
- implement zowe CLI to call the right zowe API function
- doc CLI
- automated tests
- helpful info
    - https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.5.0/reference/cmci/clientapi_overview.html
  - https://www.ibm.com/support/knowledgecenter/SSGMGV_3.1.0/com.ibm.cics.ts31.doc/dfha4/resources/urimap/dfha4_attributes.htm
  - https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.2.0/com.ibm.cics.ts.clientapi.doc/topics/clientapi_xml_elements.html
  - https://www.ibm.com/support/knowledgecenter/SSGMCP_5.5.0/reference/cpsm-restables/URIMPDEFtab.html

**Comment by tjohnsonBCM** [comment]
Sample XML for REST API (the path, host, and program attributes are all required):

```
<request>
  <create>
    <parameter name="CSD"/>
    <attributes name="ABCD" csdgroup="MYGRP" path="PATH" host="HOST" program="PROGRAM"/>
  </create>
</request>
```

Endpoint: `<host>:<port>/CICSSystemManagement/CICSDefinitionURIMap/CICCMCI2`

**Comment by MikeBauerCA** [comment]
@tjohnsonBCM should this issue be closed?
