### ISSUE TITLE
Define a CICS WEBSERVICE

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/zowe-cli-cics-plugin#58]
Create a new Zowe CLI command to define a CICS WEBSERVICE resource (`zowe cics define webservice`).

Required options:
* WEBSERVICE
* GROUP
* PIPELINE
* WSBIND

Additional options:
* DESCRIPTION
* VALIDATION(NO|YES)
* WSDLFILE

IBM documentation:
* [WEBSERVICE attributes](https://www.ibm.com/support/knowledgecenter/SSGMGV_3.1.0/com.ibm.cics.ts31.doc/dfha4/resources/webservice/dfha4_attributes.htm)
* [WEBINGRP resource table](https://www.ibm.com/support/knowledgecenter/SSGMCP_5.5.0/reference/cpsm-restables/WEBINGRPtab.html)

Example of invoking REST API to define WEBSERVICE:
`POST <host>:<port>/CICSSystemManagement/CICSDefinitionWebService/CICCMCI2`
where region name = "CICCMCI2"
with the following XML body:
```xml
<request>
  <create>
    <parameter name="CSD"/>
    <attributes DESCRIPTION="" PIPELINE="pipeline" NAME="websvc" WSBIND="/u/exampleapp/wsbind/example.log" csdgroup="MYGRP"/>
  </create>
</request>
```

**Comment by Joe-Winchester** [comment]
@bauer and @tjohnsonBCM - how's it going with the CICS WebService work ?  Is there anything that you'd like anyone from IBM to help with - a lot of the Zowe Hursley team are co-located with the CICS development lab and we'd be keen to help with this and any other CICS related work.  Tks

**Comment by tjohnsonBCM** [comment]
@Joe-Winchester Thanks for reaching out! Our team has been able to complete a few of the issues in [this milestone](https://github.com/zowe/zowe-cli-cics-plugin/milestone/21), but for those that remain and do not yet have someone assigned, help would be appreciated.
