### ISSUE TITLE
Make default protocol HTTPS in defining URIMAP

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/zowe-cli-cics-plugin#61]
To conform to the good practice of enabling security by default, this plugin should default to using the HTTPS protocol. In these places, the default is currently HTTP:
* The `protocol` option of a CICS profile (edit: split into another issue)
* The `urimap-scheme` option of the `define urimap-server`, `define urimap-pipeline`, and `define urimap-client` commands

**Comment by awharn** [comment]
Split the first item of this issue off into its own issue (#77).
