### ISSUE TITLE
zowe plugins install secure-credential-store-for-zowe-cli.tgz: npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by coolz4545** [zowe/zowe-cli-cics-plugin#93]
Hi,
I have managed to install the latest version of zowe, however getting below error when trying to install plugin secure-credential-store-for-zowe-cli.tgz. 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@5.4.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@5.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**version details**
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
***

Please help.
Thanks

**Comment by zFernand0** [comment]
Hey @coolz4545,
The Secure Credential Store plug-in has been integrated with the CLI on V2.
If you are still experiencing these issues on Zowe V2, please let us know by opening an issue on the Zowe CLI repo 😋 
https://github.com/zowe/zowe-cli/issues/new/choose
